### Задание №1
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [2]:
def validate_triangle(sides):
    for ind, side in enumerate(sides):
        second_side = sides[(ind+1)%3]
        third_side = sides[(ind+2)%3]
        if side >= second_side + third_side:
            return False
    return True

def longest_perimeter(lengths):
    sorted_lens = sorted(lengths)
    candidates = sorted_lens[-1:-4:-1]
    sorted_lens = sorted_lens[:-3]
    
    if validate_triangle(candidates):
        return sum(candidates)

    while  len(sorted_lens) != 0:
        if validate_triangle(candidates):
            return sum(candidates)
        maxi = candidates.index(max(candidates))
        candidates[maxi] = sorted_lens[-1]
    
    return 0
        

print(longest_perimeter([2, 2, 3, 4]))
print(longest_perimeter([1, 2, 3, 4, 5, 5, 10]))
        

9
14


### Задание №2
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [3]:
def greaterThan(a: int, b: int):
    first = str(a)
    second = str(b)

    min_len = min(len(first), len(second))

    for digit_ind in range(min_len):
        digit_a = int(first[digit_ind])
        digit_b = int(second[digit_ind])

        if digit_a > digit_b:
            return True
        elif digit_a == digit_b:
            if digit_ind == min_len - 1:
                if len(first) == len(second):
                    return False 

                if len(first) < len(second):
                    return greaterThan(int(first), int(second[min_len:]))
                else:
                    return greaterThan(int(first[min_len:]), int(second))
        else:
            return False

def insertion_sort(nums):
    for i in range(1, len(nums)):
        j = i - 1
        while j >= 0 and not greaterThan(nums[j], nums[j+1]):
            nums[j], nums[j+1] = nums[j+1], nums[j]
            j -= 1

def maximize(ints):
    result = str()
    insertion_sort(ints)

    for num in ints:
        result += str(num)
    
    result = result.lstrip('0')

    return result if result != '' else '0'

print(maximize([5, 3, 30, 34, 5, 9]))
print(maximize([0, 0]))
print(maximize([34323, 3432]))

95534330
0
343234323


### Задание №3
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [11]:
def sort_diagonals_secondary(in_m):
    m = in_m.copy()
    for j in range(1, len(m)):
        for i in range(0, len(m[0])):
            ti = i
            tj = j
            while tj > 0 and ti < len(m[0])-1 and m[tj][ti] < m[tj-1][ti+1]:
                m[tj][ti], m[tj-1][ti+1] = m[tj-1][ti+1], m[tj][ti]
                tj -= 1
                ti += 1
    return m

def sort_diagonals_main(in_m):
    m = in_m.copy()
    for j in range(1, len(m)):
        for i in range(0, len(m[0])):
            ti = i
            tj = j
            while tj > 0 and ti > 0 and m[tj][ti] < m[tj-1][ti-1]:
                m[tj][ti], m[tj-1][ti-1] = m[tj-1][ti-1], m[tj][ti]
                tj -= 1
                ti -= 1
    return m

In [20]:
import numpy as np
m = np.random.randint(-100, 100, size=(10, 10))

print(m)
print()
print(sort_diagonals_secondary(m))

[[-10  75  71 -61  24  50  32 -28  73 -85]
 [-77   2 -41  -6 -96 -98  43 -18 -72  57]
 [-36  55  64  39  56 -33 -86 -79 -16  82]
 [ 77 -53 -67 -91 -44  37 -65 -89 -87   8]
 [ 90  17 -40  -2 -18 -28  -6  96 -11  68]
 [-60  15 -33  60  29 -98 -87  99  65 -47]
 [-17 -27  79  34 -24 -10  70   5 -17  50]
 [-21  24 -63  25 -11  24  66 -50  85 -69]
 [ -7  79  52  36  66  43  -4 -25 -27 -90]
 [  1  17 -92  79  38  52  79 -66   0  47]]

[[-10 -77 -36 -61 -53 -96 -98 -44 -86 -85]
 [ 75   2 -41  -6 -67 -91 -33 -18 -79 -98]
 [ 71  55  24 -60 -40 -33 -18 -72 -89 -92]
 [ 77  64  17 -17 -28  -7 -65 -24 -87 -11]
 [ 90  39  15 -27  24 -63 -16 -87   8   5]
 [ 50  32 -21  37 -28  -6 -11  24  38 -50]
 [ 56  -2  60   1  17 -10  66  43 -47 -25]
 [ 43  73  29  25  36  70  65 -17  50 -69]
 [ 79  34  52  82  79  66  -4  79 -66 -90]
 [ 79  57  96  99  68  52  85 -27   0  47]]
