### Задание №1
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [2]:
def validate_triangle(sides):
    for ind, side in enumerate(sides):
        second_side = sides[(ind+1)%3]
        third_side = sides[(ind+2)%3]
        if side >= second_side + third_side:
            return False
    return True

def longest_perimeter(lengths):
    sorted_lens = sorted(lengths)
    candidates = sorted_lens[-1:-4:-1]
    sorted_lens = sorted_lens[:-3]
    
    if validate_triangle(candidates):
        return sum(candidates)

    while  len(sorted_lens) != 0:
        if validate_triangle(candidates):
            return sum(candidates)
        maxi = candidates.index(max(candidates))
        candidates[maxi] = sorted_lens[-1]
    
    return 0
        

print(longest_perimeter([2, 2, 3, 4]))
print(longest_perimeter([1, 2, 3, 4, 5, 5, 10]))
        

9
14


### Задание №2
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [3]:
def greaterThan(a: int, b: int):
    first = str(a)
    second = str(b)

    min_len = min(len(first), len(second))

    for digit_ind in range(min_len):
        digit_a = int(first[digit_ind])
        digit_b = int(second[digit_ind])

        if digit_a > digit_b:
            return True
        elif digit_a == digit_b:
            if digit_ind == min_len - 1:
                if len(first) == len(second):
                    return False 

                if len(first) < len(second):
                    return greaterThan(int(first), int(second[min_len:]))
                else:
                    return greaterThan(int(first[min_len:]), int(second))
        else:
            return False

def insertion_sort(nums):
    for i in range(1, len(nums)):
        j = i - 1
        while j >= 0 and not greaterThan(nums[j], nums[j+1]):
            nums[j], nums[j+1] = nums[j+1], nums[j]
            j -= 1

def maximize(ints):
    result = str()
    insertion_sort(ints)

    for num in ints:
        result += str(num)
    
    result = result.lstrip('0')

    return result if result != '' else '0'

print(maximize([5, 3, 30, 34, 5, 9]))
print(maximize([0, 0]))
print(maximize([34323, 3432]))

95534330
0
343234323


### Задание №3
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [4]:
import numpy as np

In [5]:
def get_diagonals(matrix):
    diagonals = list()

    rows = len(matrix)
    cols = len(matrix[0])

    # fill diagonals from first to right main
    for i in range(cols):
        col = i
        row = 0
        diagonal = list()
        while col >= 0 and row < rows:
            diagonal.append(matrix[row][col])
            col -= 1
            row += 1
        diagonals.append(diagonal)

    # fill diagonals from right main + 1 to last
    for i in range(1, rows):
        col = cols - 1
        row = i
        diagonal = list()
        while cols >= 0 and row < rows:
            diagonal.append(matrix[row][col])
            col -= 1
            row += 1
        diagonals.append(diagonal)
    
    return diagonals

In [6]:
def build_matrix_from_diagonals(diagonals, rows, cols):

    matrix = list()
    before_main = diagonals[:(len(diagonals)+1)//2]
    after_main = diagonals[(len(diagonals)+1)//2:]

    for row in range(rows):
        matrix_row = list()

        # fill N-th row with N-th number from every before main diagonal
        for diag in before_main:
            if len(diag) < row + 1:
                continue
            matrix_row.append(diag[row])

        # fill N-th row with [row - 1 -> 0] element from [0 -> row - 1] diagonal
        if row != 0:
            diag = 0
            ind = row - 1
            for i in range(row):
                matrix_row.append(after_main[diag][ind])
                diag += 1
                ind -= 1
        matrix.append(matrix_row)
    return np.matrix(matrix)

In [7]:
def sort_diagonals(matrix):
    diagonals = get_diagonals(matrix)

    diagonals = list(map(sorted, diagonals))

    return build_matrix_from_diagonals(diagonals, len(matrix), len(matrix[0]))

In [8]:
m = np.random.randint(0, 10, size=(5, 5))

print(m)
print()
print(sort_diagonals(m))

[[4 8 4 4 1]
 [6 0 2 4 1]
 [9 2 5 2 6]
 [3 2 2 5 4]
 [0 7 0 7 6]]

[[4 6 0 2 0]
 [8 4 2 1 1]
 [9 3 2 2 0]
 [4 4 2 5 4]
 [5 7 6 7 6]]
